name: Build

on: 
  - push
  - workflow_dispatch

jobs: 
  build-and-publish: 
    name: Build and publish docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/bigspaceships/website:latest